### PR TITLE
Add classification examples.

### PR DESCRIPTION
**Pull request by markpbaggett**
This adds all the classification examples from our Islandora metadata.

### CODE REVIEW

**Review by mlhale7 — COMMENTED** [review]
@markpbaggett For classification, I had a value related concern that I wanted to mention. Some values include dates and others do not. For instance LD5296 .W6 and LD5291.8 .T67 1966. Technically classification is different than a shelf locator or call number and the year should not be included on this value. I'll open a ticket for this.

Otherwise, I wanted to mention that technically all classification values follow lcc even if this is not identified with an authority. I can open a ticket to fix this. Let me know if this is something we could also just knowingly map over (all values should be associated with lcc) rather than taking the time to do the metadata edits.

Let me know if there's anything we should incorporate into this doc before merging and if you have any suggestions.

**Comment by markpbaggett** [comment]
@mlhale7, I added a commit but am not sure that's good enough.  Let me know what you think.

**Review by mlhale7 — COMMENTED** [review]
Maybe change the text to the following?

Some records have values with years that need to be removed because these values aren't consistent with classification values. The values present currently are shelfLocators rather than purely subject-focused values. Islandora's recommendation to map classification values to dc:subject highlights this focus. An example record that requires edits is `harp 1 <https://digital.lib.utk.edu/collections/islandora/object/harp%3A1/datastream/MODS>`_

If you could also note in the "No authority" section that the values follow lcc despite not having this attribute, that would be helpful too.

**Comment by markpbaggett** [comment]
Okay, done.

**Comment by mlhale7** [comment]
@markpbaggett - thanks for the edits.

**Pull request merged**
